---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
Dopamine <- read_delim("data/Dopamine.csv", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
View(Dopamine)
```

```{r}
## Recoding Dopamine$Treat
Dopamine$Treat <- factor(Dopamine$Treat)


```

```{r}
summary(Dopamine)
```

```{r}
library(ggplot2)
ggplot(data=Dopamine)+
 geom_boxplot(mapping=aes(x= Treat, y = Dopa, fill=Treat))
```
##statistiques

H0: dopamine controle = dopamine toluène
H1: dopamine controle $\ne$ dopamine toluène
                     ( veut dire " différent" )

Calculer les résidus

```{r}
library("dplyr")
Dopamine %>% mutate(Dopa.res = Dopa - ave(Dopa, Treat)) -> Dopamine
```

#Test quantile quantile
```{r}
car::qqPlot(Dopamine$Dopa.res, distribution = "norm",
  envelope = 0.95, col = "Black", ylab = "Dopa")
```

-> les résidus suivent +- une distribution normale -> test de student

```{r}
t.test(Dopa ~ Treat, data = Dopamine,
  alternative = "two.sided", conf.level = 0.95, var.equal = TRUE)
```

-> 

avec test W
```{r}
#wilcox.test(Dopa ~ Treat, data = Dopamine,
 # alternative = "two.sided", conf.level = 0.95)
```

